name    'puppet-phpmyadmin'
version '0.0.3'
source  'https://github.com/leoc/puppet-phpmyadmin'
author  'Arthur Leonard Andersen'
license 'GPLv3'
summary 'Puppet PhpMyAdmin Module'
description 'Module to install PhpMyAdmin using puppet.'
project_page 'https://github.com/leoc/puppet-phpmyadmin/'
